version: '3'
services:
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:80
    volumes:
      - ./webapp:/opt/webapp
    ports:
      - "80:80"
    env_file: .env
    depends_on:
      - db
  db:
    image: postgres:latest
    ports:
      - "5432:5432"